<?php
/**
 * @file
 * Code for the Futurium_ISA feature.
 */

include_once 'futurium_isa.features.inc';

/**
* Implements hook_entity_info_alter().
*/
function futurium_isa_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['node_header'] = array(
    'label' => t('Node Header'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_field_default_field_bases_alter().
 */
function futurium_isa_field_default_field_bases_alter(&$fields) {
  foreach ($fields as $field_name => &$field_config) {
    $db_field_config = field_info_field($field_name);
    if (isset($field_config['settings']['default_image'])) {
      // Field default picture may not be set from the feature itself, due to
      // possible conflict with pre-existing fid's, so we need to make sure it
      // if it is set, it shouldn't be marked as overriden.
      if ($field_config['settings']['default_image'] != $db_field_config['settings']['default_image']) {
        $field_config['settings']['default_image'] = $db_field_config['settings']['default_image'];
      }
    }
  }
}

/**
 * Implements relation_label_autocomplete_alter().
 */
function futurium_isa_relation_label_autocomplete_alter(&$label) {
  switch ($label) {
    case 'supports':
      $label = 'that supports';
      break;

  }
}

/**
 * Implements relation_content_type_autocomplete_alter().
 */
function futurium_isa_relation_content_type_autocomplete_alter(&$content_type) {
  switch ($content_type) {
    case 'Ideas':
      $content_type = 'Idea';
      break;

    case 'Futures':
      $content_type = 'Future';
      break;
  }
}

/**
 * Implements hook_user_default_permissions_alter().
 *
 * Add all permissions to administrator role.
 */
function futurium_isa_user_default_permissions_alter(&$permissions) {
  foreach ($permissions as &$permission) {
    $permission['roles']['administrator'] = 'administrator';
  }
}

/**
 * Take actions before saving rate widget to the database.
 *
 * @param object $widget Widget object
 * @param array $values Values from $form_state['values']
 */
function futurium_isa_rate_widget_insert(&$widget, $values) {
  if ($widget->theme == 'rate_template_fivestar') {
    $widget->css = drupal_get_path('module', 'rate') . '/templates/fivestar/fivestar.css';
    $widget->js = drupal_get_path('module', 'rate') . '/templates/fivestar/fivestar.js';
  }
}

/**
 * Take actions before updating rate widget.
 *
 * @param object $widget Widget object
 * @param array $values Values from $form_state['values']
 */
function futurium_isa_rate_widget_update(&$widget, $values) {
  if ($widget->theme == 'rate_template_fivestar') {
    $widget->css = drupal_get_path('module', 'rate') . '/templates/fivestar/fivestar.css';
    $widget->js = drupal_get_path('module', 'rate') . '/templates/fivestar/fivestar.js';
  }
}
