<?php
/**
 * @file
 * Code for the Futurium Graph feature.
 */

include_once 'futurium_graph.features.inc';

/**
 * Implements template_preprocess_html().
 */
function futurium_graph_preprocess_html(&$variables) {
  $item = menu_get_item();

  if ($item['path'] == 'node/%/graph' && isset($item['original_map'][1])) {
    if ($obj = node_load($item['original_map'][1])) {
      $class = 'node-type-' . drupal_html_class($obj->type);
    }
  }

  if (isset($class)) {
    $variables['classes_array'][] = $class;
  }
}

/**
 * Implements hook_js_alter().
 *
 * Remove the springyui.js file.
 */
function futurium_graph_libraries_info_alter(&$libraries) {
  if (isset($libraries['springy'])) {
    if ($idx = array_search('springyui.js', $libraries['springy']['files']['js'])) {
      unset($libraries['springy']['files']['js'][$idx]);
    }
  }
}

/**
 * Implements hook_js_alter().
 *
 * Include a modified version of the springyui.js.
 */
function futurium_graph_preprocess_page(&$vars) {
  $item = menu_get_item();
  if ($item['path'] == 'node/%/graph') {
    $path = drupal_get_path('module', 'futurium_graph') . '/js/springyui.js';
    drupal_add_js($path);
  }
}
