<?php

/**
 * @file
 * Installs the Futurium D4EU feature.
 */

/**
 * Implements hook_enable().
 */
function futurium_core_enable() {
  $t = get_t();
  drupal_set_message($t('Futurium core feature is now active on your site.'));
}

/**
 * Implements hook_disable().
 */
function futurium_core_disable() {
  $t = get_t();
  drupal_set_message($t('Futurium core feature is now disabled on your site.'));
}
