<?php
/**
 * @file
 * Code for the Futurium Groups feature.
 */

include_once 'futurium_groups.features.inc';

/**
 * Administrative form.
 */
function futurium_groups_administration() {

  $default = variable_get('futurium_groups_rewrite_group_urls', FALSE);

  $form['futurium_groups_rewrite_group_urls'] = array(
    '#title' => t("Rewrite group urls"),
    '#type' => 'checkbox',
    '#default_value' => $default,
    '#description' => "Enables rewrite of the group paths.",
  );

  return system_settings_form($form);

}


function futurium_groups_menu() {

  $items['admin/config/futurium_groups'] = array(
    'title' => 'Futurium groups settings',
    'description' => 'Futurium groups settings and administration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('futurium_groups_administration'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Initialize group context.
 */
function futurium_groups_init() {
  $variables = array();
  $item = menu_get_item();
  $node = menu_get_object();
  if ($node) {
    // Group homepage.
    if ($node->type == 'futurium_group' && $item['path'] == 'node/%') {
      $variables['active_group'] = $node;
      $variables['page_type'] = 'homepage';
      $variables['page_context'] = $item;
    }
    else {
      // Group content.
      if (og_is_group_content_type('node', $node->type)) {
        $groups = og_get_entity_groups('node', $node);
        $master = FALSE;
        foreach ($groups as $entity_type => $og_memberships) {
          foreach ($og_memberships as $membership_id => $entity_id) {
            if ($entity_type == 'node') {
              $group_node = node_load($entity_id);
              // Set default group.
              if (empty($variables['active_group'])) {
                $default_group = $group_node;
                $variables['active_group'] = $group_node;
              }
              $variables['groups'][] = $group_node;
            }
          }
        }
        $variables['page_type'] = 'group_content';
        $variables['page_context'] = $item;
      }
    }
  }
  if (!$node) {
    if (substr($item['path'], 0, 6) == 'node/%') {
      $node = node_load(arg(1));
      $variables['active_group'] = $node;
      $variables['page_context'] = $item;
      $variables['page_type'] = $item['page_callback'];
    }
  }
  drupal_alter('futurium_groups_context', $variables);
  context_set("futurium_groups", $variables);
}

function futurium_groups_form_node_form_alter($form, $form_state, $form_id) {
  $q = drupal_get_query_parameters();
  if (!empty($q) && isset($q['og_group_ref'])) {
    $form["og_group_ref"][LANGUAGE_NONE]['attributes']['style'] = 'display:none';
  }
}
